services:
    flask:
        build:
            context: ./app/
            dockerfile: Dockerfile
        env_file: .env
        ports:
          - 80:80
        volumes:
          - ./volume/:/app/volume
        restart: always

    bgutil-provider:
      image: brainicism/bgutil-ytdlp-pot-provider
      restart: always